channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake-minimal==7.30.1
  - bbmap=39.01
  - git
  - kma==1.4.9
  - pip
  - pip:
    #- jsonschema<4
    #- warlock==1.3.3
    - pytest
    - pytest-cov
    - pytest-profiling
    - coverage
    - pyyaml
    - argh
    - watchdog
    - jsonschema==v4.18.0a10
    - bifrostlib
    - resfinder
    - -e .