#-Basic info----------------------------------------------------------------------------------------
display_name: cge_resfinder
name: &name cge_resfinder__v2_2_1__d98c13b
version:
  schema: ["v2_1_0"]
  code: v2_2_1
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  target: [sample]
  description: >
    This preforms read based mapping against the resfinder DB's. The options show the species entries 
    which will be attempted for mlst with key originating from the species DB. This is done against 
    the cge_db using kma mode. 
#---------------------------------------------------------------------------------------------------

#-Category info-------------------------------------------------------------------------------------
category: [resistance]
#---------------------------------------------------------------------------------------------------

#-Install-------------------------------------------------------------------------------------------
install:
  path: # Set by install program
  dockerfile: docker://ssidk/bifrost_cge_resfinder
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
  #adapters_fasta: "/bifrost/components/bifrost_min_read_check/resources/adapters.fasta"
  resfinder_db: "/bifrost/components/bifrost_cge_resfinder/resources/resfinder_db"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    categories:
      paired_reads:
        summary:
          data:
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files: []
  sample:
    categories:
      resistance:
        summary:  # see sample_component summary
        component:
          _id: 
          date:  # ObjectId
    report:
      resistance:
        title: "Resistance"
        info: *name
        columns: 
          - {id: "gene", name: "gene"}
          - {id: "coverage", name: "%cov"}
          - {id: "identity", name: "%id"}
          - {id: "variants", name: "# of variants"}
        data: []
  sample_component:
    summary:
      genes: 
    results:
      cge_resfinder/data_yaml: {}

#---------------------------------------------------------------------------------------------------
